condense_wildcard_suffixes = true
edition = "2024"
fn_single_line = false
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_modules = true
style_edition = "2024"
wrap_comments = true
