[package]
name = "libmock"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
libc = "0.2.176"

[lib]
crate-type = ["cdylib", "lib"] # This is crucial!
